language: node_js
env:
  global:
  - DISABLE_NOTIFIER=true
node_js:
  - "4.4.3"
before_script:
  # http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bower install
