version: '2'

services:
  gulp:
    extends:
      file: docker-common-node.yml
      service: base
    ports:
     - "3000:3000"
     - "3001:3001"
    command: npm run gulp

  test:
    extends:
      file: docker-common-node.yml
      service: base
    command: npm test

  lint:
    extends:
      file: docker-common-node.yml
      service: base
    command: npm run gulp lint

  demo:
    extends:
      file: docker-common-node.yml
      service: base
    ports:
     - "5000:5000"
    command: npm start
